#!/bin/zsh

#

for arg; do
  if [[ ! -f $arg ]]; then
    echo "Error: $arg does not exist." >&2
    continue
  elif [[ ! -r $arg ]]; then
    echo "Error: $arg is not readable." >&2
    continue
  fi
  case $(file --mime-type --brief $arg) in
    text/html|text/htm) browser $arg &!;;
    text/*|inode/x-empty) ${EDITOR:-vi} $arg;;
    application/zip)
      case $(file --brief $arg) in
	Microsoft\ OOXML) libreoffice $arg &!;;
	*) xdg-open $arg &!;;
      esac;;
    *) xdg-open $arg &!;;
  esac
done
